---
  - name: httpd.conf file
    copy: src=httpd.conf dest=/etc/httpd/conf/
    become: true
    notify:
        - restart httpd service
   
  - name: send copy.html file
    copy: src=copy.html dest=/var/www/html/
    become: true    
