---
- hosts: all
  become: yes
  tasks:
      - name: update centos system
        become: yes
        yum:
          name: '*'  
          state: latest
            #when: ansible_facts['distribution'] == 'Centos'    
